plugins:
- sem_kge

job:
  type: search
  #external_tracking:
  #  weights-and-biases:
  #    project: sem_kge
  #    group: transt
      
search.type: ax

dataset.name: fb15k-237-typed

train:
  max_epochs: 75

valid:
  every: 5
  early_stopping:
    min_threshold:
      epochs: 15
      metric_value: 0.15

eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example

import: [transt]


ax_search:
  num_trials: 30
  num_sobol_trials: 10
  parameters:
  
    # model
    - name: model
      type: fixed
      value: transt
      
    # training hyperparameters
    - name: train.batch_size
      type: fixed
      value: 128 # [128, 256, 512, 1024]
      is_ordered: True
    - name: train.type
      type: fixed
      value: negative_sampling
    - name: train.optimizer
      type: choice
      values: [Adam, Adagrad]
    - name: train.loss
      type: choice
      values: [margin_ranking, kl] #TODO check if this makes sense
    - name: train.optimizer_args.lr
      type: range
      bounds: [0.0001, 1.]
      log_scale: True
    - name: train.lr_scheduler
      type: fixed
      value: ReduceLROnPlateau
    - name: train.lr_scheduler_args.mode
      type: fixed
      value: max
    - name: train.lr_scheduler_args.factor
      type: fixed
      value: 0.95
    - name: train.lr_scheduler_args.threshold
      type: fixed
      value: 0.0001
    - name: train.lr_scheduler_args.patience
      type: range
      bounds: [0, 10]

    # embedding dimension
    - name: lookup_embedder.dim
      type: choice 
      values: [128, 256, 512]
      is_ordered: True
      
    # embedding initialization
    - name: lookup_embedder.initialize
      type: choice
      values: [xavier_normal_, xavier_uniform_, normal_, uniform_]  
    - name: lookup_embedder.initialize_args.normal_.mean
      type: fixed
      value: 0.0
    - name: lookup_embedder.initialize_args.normal_.std
      type: range
      bounds: [0.00001, 1.0]
      log_scale: True
    - name: lookup_embedder.initialize_args.uniform_.a
      type: range
      bounds: [-1.0, -0.00001]
    - name: lookup_embedder.initialize_args.xavier_uniform_.gain
      type: fixed
      value: 1.0
    - name: lookup_embedder.initialize_args.xavier_normal_.gain
      type: fixed
      value: 1.0
  
    # embedding regularization
    - name: lookup_embedder.regularize
      type: choice
      values: ['', 'l3', 'l2', 'l1']
      is_ordered: True
    - name: lookup_embedder.regularize_args.weighted
      type: choice
      values: [True, False]
    - name: transt.entity_embedder.regularize_weight
      type: range
      bounds: [1.0e-20, 1.0e-01]
      log_scale: True
    - name: transt.relation_embedder.regularize_weight
      type: range
      bounds: [1.0e-20, 1.0e-01]
      log_scale: True

    # embedding dropout
    - name: transt.entity_embedder.dropout
      type: range
      bounds: [0., 0.5] #[-0.5, 0.5]
    - name: transt.relation_embedder.dropout
      type: range
      bounds: [0., 0.5]

    # training-type specific hyperparameters
    - name: negative_sampling.num_negatives_s #train_type = negative_sampling
      type: range                             #train_type = negative_sampling
      bounds: [1, 1000]                       #train_type = negative_sampling
      log_scale: True                         #train_type = negative_sampling
    - name: negative_sampling.num_negatives_o #train_type = negative_sampling
      type: range                             #train_type = negative_sampling
      bounds: [1, 1000]                       #train_type = negative_sampling
      log_scale: True                         #train_type = negative_sampling
      
    # margin
    - name: train.loss_arg
      type: range
      bounds: [0.0, 10.0]
  
    # model-specific entries
    - name: transt.l_norm
      type: choice
      values: [1.0, 2.0]
      is_ordered: True
    - name: transt.entity_embedder.normalize.p
      type: choice
      values: [-1.0, 2.0]
    - name: transt.relation_embedder.normalize.p
      type: choice
      values: [-1.0, 2.0]
      
    - name: transt.lambda_head
      type: range
      bounds: [0., 1.]
    - name: transt.lambda_relation
      type: range
      bounds: [0., 1.]
    - name: transt.lambda_tail
      type: range
      bounds: [0., 1.]
    - name: transt.learn_lambda
      type: choice
      values: [True, False]
    - name: transt.rho
      type: range
      bounds: [0.5, 0.8]
      
      

