modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]

job:
  type: search

search.type: ax

dataset.name: fb15k-237-typed

train:
  max_epochs: 125
  auto_correct: true

valid:
  every: 5
  early_stopping:
    min_threshold:
      epochs: 15
      metric_value: 0.1

eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example

import:
- transe
- type_attentive_embedder

reciprocal_relations_model:
  base_model:
    type: transe
transe:
  entity_embedder:
    type: type_attentive_embedder

search.on_error: continue

ax_search:
  num_trials: 45
  num_sobol_trials: 15
  parameters:
  
    # model
    - name: model
      type: fixed
      value: reciprocal_relations_model
      
    # training hyperparameters
    - name: train.batch_size
      type: choice
      values: [32, 64, 128] # [128, 256, 512, 1024]
      is_ordered: True
    - name: train.type
      type: fixed
      value: negative_sampling
    - name: train.optimizer
      type: choice
      values: [Adam, Adagrad]
      
      
      #TODO check if this makes sense
    - name: train.loss
      type: choice
      values: [margin_ranking, kl] 
      
      
    - name: train.optimizer_args.lr
      type: range
      bounds: [0.0001, 1.]
      log_scale: True
    - name: train.lr_scheduler
      type: fixed
      value: ReduceLROnPlateau
    - name: train.lr_scheduler_args.mode
      type: fixed
      value: max
    - name: train.lr_scheduler_args.factor
      type: fixed
      value: 0.95
    - name: train.lr_scheduler_args.threshold
      type: fixed
      value: 0.0001
    - name: train.lr_scheduler_args.patience
      type: range
      bounds: [0, 10]

    # embedding dimension
    - name: lookup_embedder.dim
      type: choice 
      values: [32, 64, 128, 256, 512]
      is_ordered: True
      
    # embedding initialization
    - name: lookup_embedder.initialize
      type: choice
      values: [xavier_normal_, xavier_uniform_, normal_, uniform_]  
    - name: lookup_embedder.initialize_args.normal_.mean
      type: fixed
      value: 0.0
    - name: lookup_embedder.initialize_args.normal_.std
      type: range
      bounds: [0.00001, 1.0]
      log_scale: True
    - name: lookup_embedder.initialize_args.uniform_.a
      type: range
      bounds: [-1.0, -0.00001]
    - name: lookup_embedder.initialize_args.xavier_uniform_.gain
      type: fixed
      value: 1.0
    - name: lookup_embedder.initialize_args.xavier_normal_.gain
      type: fixed
      value: 1.0
  
    # embedding regularization
    - name: lookup_embedder.regularize
      type: choice
      values: ['', 'l3', 'l2', 'l1']
      is_ordered: True
    - name: lookup_embedder.regularize_args.weighted
      type: choice
      values: [True, False]
    - name: transe.entity_embedder.base_embedder.regularize_weight
      type: range
      bounds: [1.0e-20, 1.0e-01]
      log_scale: True
    - name: transe.entity_embedder.type_embedder.regularize_weight
      type: range
      bounds: [1.0e-20, 1.0e-01]
      log_scale: True
    - name: transe.relation_embedder.regularize_weight
      type: range
      bounds: [1.0e-20, 1.0e-01]
      log_scale: True

    # embedding dropout
    - name: transe.entity_embedder.base_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]
    - name: transe.entity_embedder.type_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]
    - name: transe.relation_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]

    # training-type specific hyperparameters
    - name: negative_sampling.num_negatives_s #train_type = negative_sampling
      type: range                             #train_type = negative_sampling
      bounds: [1, 1000]                       #train_type = negative_sampling
      log_scale: True                         #train_type = negative_sampling
    - name: negative_sampling.num_negatives_o #train_type = negative_sampling
      type: range                             #train_type = negative_sampling
      bounds: [1, 1000]                       #train_type = negative_sampling
      log_scale: True                         #train_type = negative_sampling
      
    # margin
    - name: train.loss_arg
      type: range
      bounds: [0.0, 10.0]
  
    # model-specific entries
    
    - name: transe.entity_embedder.attn_nhead
      type: choice
      values: [1, 2, 4, 8]
      is_ordered: True
      

