complex:
  entity_embedder:
    dropout: 0.07931799348443747
    regularize_weight: 9.584175626202284e-13
  relation_embedder:
    dropout: 0.05643956921994686
    regularize_weight: 0.022858621200283015
dataset:
  name: codex-s/
  num_entities: 2034
  num_relations: 42
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
import:
- reciprocal_relations_model
- complex
lookup_embedder:
  dim: 512
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.0003706650808601012
    uniform_:
      a: -0.2092997908254619
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize: ''
  regularize_args:
    weighted: true
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
reciprocal_relations_model:
  base_model:
    type: complex
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 400
  optimizer: Adam
  optimizer_args:
    lr: 0.00033858206813454155
  type: 1vsAll
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

