modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]
job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transt
dataset:
  name: wnrr-typed
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- transt
lookup_embedder:
  dim: 64
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.00036174939032954854
    uniform_:
      a: -0.393658811201549
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
model: transt 
negative_sampling:
  num_samples:
    o: 158
    p: -1
    s: 70
train:
  auto_correct: true
  batch_size: 128
  loss: margin_ranking
  loss_arg: 3.
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  max_epochs: 400
  optimizer_args:
    lr: 0.2532720169185861
  type: negative_sampling
  
transe:
  entity_embedder:
    dropout: 0.2519204934424376
    regularize_weight: 2.1299293567133326e-07
  relation_embedder:
    regularize_weight: 8.992034045083661e-13
  l_norm: 2.
reciprocal_relations_model:
  base_model:
    type: transe
type_prior:
  lambda_head: 0.       #0.5
  lambda_relation: 1.   #0.5
  lambda_tail: 0.       #0.5
  learn_lambda: True
  base_model:
    type: reciprocal_relations_model
    base_model:
      type: transe
      
valid:
  every: 5
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

