modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]
job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transe
dataset:
  name: fb15k-237
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
  num_workers: 2
import:
- transe
- reciprocal_relations_model
model: reciprocal_relations_model
negative_sampling:
  num_samples:
    s: 61
    p: -1
    o: 192
train:
  auto_correct: true
  batch_size: 128
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  max_epochs: 400
  optimizer: Adam
  optimizer_args:
    lr: 0.0003
  type: negative_sampling
lookup_embedder.dim: 128
reciprocal_relations_model:
  base_model:
    type: transe
transe:
  l_norm: 2.0
  relation_embedder:
    regularize_weight: 1.8180176908040284e-07
entity_ranking:
  chunk_size: 256
valid:
  every: 1
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

