modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]
job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transe
dataset:
  name: fb15k-237-typed
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
  num_workers: 2
import:
- transe
- type_prior_embedder
- reciprocal_relations_model
- iaf_embedder
model: reciprocal_relations_model
negative_sampling:
  num_samples:
    s: 700
    p: -1
    o: 200
  shared: True
  implementation: batch
train:
  auto_correct: true
  batch_size: 128
  loss_arg: 2.5
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 9
    threshold: 0.0001
  max_epochs: 400
  optimizer: Adam
  optimizer_args:
    lr: 0.003
  type: negative_sampling
reciprocal_relations_model:
  base_model:
    type: transe
    entity_embedder:
      type: type_prior_embedder
      dim: 128
      prior_embedder:
        type: iaf_embedder
        direction: density-estimation
        context_dim: 96
        hidden_dims:
          - 384
          - 384
        base_embedder.scale_embedder.initialize: constant_
        base_embedder.scale_embedder.initialize_args.val: 0.225
    l_norm: 2.0
    relation_embedder:
      dim: 128
      regularize_weight: 1.75e-11
entity_ranking:
  chunk_size: 1024
valid:
  every: 5
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

