modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]
job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transt
dataset:
  name: fb15k-237-typed
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- type_linkprior
- transe
- reciprocal_relations_model
lookup_embedder:
  dim: 128
  initialize: xavier_uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 4.314427606172353e-05
    uniform_:
      a: -0.6992891560219134
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize: 'lp'
model: type_linkprior 
negative_sampling:
  num_samples:
    o: 125
    p: -1
    s: 137
train:
  auto_correct: true
  batch_size: 128
  loss_arg: 4.610417988151312
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 2
    threshold: 0.0001
  max_epochs: 400
  optimizer: Adagrad
  optimizer_args:
    lr: 0.04213990046519199
  type: negative_sampling
transe:
  entity_embedder:
    dropout: -0.12961751874536276
    regularize_weight: 1.0578209241264233e-12
    normalize.p: 2.0
  relation_embedder:
    dropout: 0.11680278182029724
    regularize_weight: 2.7150262251210395e-14
    normalize.p: -1.0
  l_norm: 1.0
reciprocal_relations_model:
  base_model:
    type: transe
type_linkprior:
  rho: 0.7314586686901748
  lambda_head: 0.352859390899539
  lambda_relation: -0.46099785156548023
  lambda_tail: 0.9701304156333208
  learn_lambda: False
  base_model:
    type: reciprocal_relations_model
    base_model:
      type: transe
valid:
  every: 5
  early_stopping:
    patience: 5
    min_threshold:
      epochs: 50
      metric_value: 0.05

