modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]
job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transt
dataset:
  name: fb15k-237-typed
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- transt
- transt_embedder
transt_embedder:
  dim: 300
  nr_embeds: 5
lookup_embedder:
  dim: 300
model: transt 
train:
  batch_size: 128
  loss: margin_ranking
  loss_arg: 3.5
  max_epochs: 400
  optimizer: SGD
  optimizer_args:
    lr: lr: 0.00025
  type: negative_sampling
transt:
  lambda_head: 1.
  lambda_relation: 0.
  lambda_tail: 1.
  l_norm: 1.0
  entity_embedder:
    type: growing_embedder
    normalize:
      p: 2.
valid:
  every: 10
  early_stopping:
    patience: 10

