plugins:
- sem_kge
job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transt
dataset:
  name: wnrr-typed
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- transt
lookup_embedder:
  dim: 50                       # 50
model: transt 
train:
#  auto_correct: true
  batch_size: 128
  loss: margin_ranking
  loss_arg: 3.                  # 3.
  max_epochs: 400
  optimizer_args:
    lr: 0.1                     # 0.001
  type: negative_sampling
transt:
  lambda_head: 0.               # 0
  lambda_relation: 1.           # 1 (but sometimes 0, depending? unclear when)
  lambda_tail: 0.               # 0 
  l_norm: 1.0                   # 1
  entity_embedder:
    normalize:
      p: 2.
valid:
  every: 5
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

