modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]
job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transe-gaussian
dataset:
  name: fb15k-237
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- transe
- pyro_xform_embedder
model: transe 
negative_sampling:
  num_samples:
    o: 192
    p: -1
    s: 61
train:
  auto_correct: true
  batch_size: 128
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  max_epochs: 400
  optimizer: Adam
  optimizer_args:
    lr: 0.0003
  type: negative_sampling
lookup_embedder:
  dim: 64
pyro_xform_embedder:
  dim: 64
  context_dim: 32
  hidden_dims:
    - 96
    - 96
transe:
  entity_embedder:
    type: lookup_embedder
  relation_embedder:
    type: pyro_xform_embedder
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

