modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]

job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transe

dataset:
  name: codex-s-typed
  num_entities: 2034
  num_relations: 42
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
import:
- transe
- type_attentive_embedder
- reciprocal_relations_model
lookup_embedder:
  dim: 512
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 7.387281885290558e-05
    uniform_:
      a: -0.860686260168301
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
model: reciprocal_relations_model
negative_sampling:
  num_samples:
    o: 56
    s: 2
  shared: True
  implementation: batch
reciprocal_relations_model:
  base_model:
    type: transe
    entity_embedder:
      base_embedder:
        regularize_weight: 1.3175179879955912e-07
      #type_embedder:
      #  regularize_weight: 1.3175179879955912e-07
train:
  auto_correct: true
  batch_size: 128
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 6
    threshold: 0.0001
  max_epochs: 400
  optimizer:
    default:
      args.lr: 0.04121772717931592
    type_attentive:
      regex: .*type_attentive_embedder.self_attn.*
      args.lr: 0.008
  lr_warmup: 5
  type: negative_sampling
transe:
  entity_embedder:
    type: type_attentive_embedder
    mi_min_threshold: 7.5
  l_norm: 2.0
  relation_embedder:
    regularize_weight: 3.7237496170376805e-18
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
entity_ranking:
  chunk_size: 1024
