modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]

job:
  type: search

search:
  type: ax
  on_error: continue

dataset.name: codex-s-typed

train:
  max_epochs: 400
  auto_correct: true

valid:
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  filter_with_test: True
  early_stopping:
    patience: 10
    min_threshold:
      epochs: 50
      metric_value: 0.05

eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example

import:
- transe
- type_attentive_embedder
- reciprocal_relations_model

reciprocal_relations_model:
  base_model:
    type: transe
transe:
  entity_embedder:
    type: type_attentive_embedder


ax_search:
  num_trials: 40
  num_sobol_trials: 20
  parameters:

    # model
    - name: model
      type: fixed
      value: reciprocal_relations_model

    # training hyperparameters
    - name: train.batch_size
      type: fixed
      value: 128
    - name: train.type
      type: fixed
      value: negative_sampling
    - name: train.optimizer
      type: fixed
      value: Adam

    - name: train.loss
      type: fixed
      value: kl

    - name: train.optimizer.default.args.lr
      type: range
      bounds: [0.0001, 1.]
      log_scale: True
    - name: train.lr_scheduler
      type: fixed
      value: ReduceLROnPlateau
    - name: train.lr_scheduler_args.mode
      type: fixed
      value: max
    - name: train.lr_scheduler_args.factor
      type: fixed
      value: 0.95
    - name: train.lr_scheduler_args.threshold
      type: fixed
      value: 0.0001
    - name: train.lr_scheduler_args.patience
      type: range
      bounds: [0, 10]

    # embedding dimension
    - name: lookup_embedder.dim
      type: fixed
      value: 512

    # embedding initialization
    - name: lookup_embedder.initialize
      type: fixed
      value: xavier_normal_
    - name: lookup_embedder.initialize_args.normal_.mean
      type: fixed
      value: 0.0
    - name: lookup_embedder.initialize_args.normal_.std
      type: fixed
      value: 0.38502710782632205
    - name: lookup_embedder.initialize_args.xavier_normal_.gain
      type: fixed
      value: 1.0

    # embedding regularization
#    - name: lookup_embedder.regularize
#      type: choice
#      values: ['', 'l3', 'l2', 'l1']
#      is_ordered: True
#    - name: lookup_embedder.regularize_args.weighted
#      type: choice
#      values: [True, False]
#    - name: transe.entity_embedder.base_embedder.regularize_weight
#      type: range
#      bounds: [1.0e-20, 1.0e-01]
#      log_scale: True
#    - name: transe.entity_embedder.type_embedder.regularize_weight
#      type: range
#      bounds: [1.0e-20, 1.0e-01]
#      log_scale: True
#    - name: transe.relation_embedder.regularize_weight
#      type: range
#      bounds: [1.0e-20, 1.0e-01]
#      log_scale: True

    # embedding dropout
    - name: transe.entity_embedder.base_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]
    - name: transe.entity_embedder.type_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]
    - name: transe.relation_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]

    # training-type specific hyperparameters
    - name: negative_sampling.num_negatives_s #train_type = negative_sampling
      type: range                             #train_type = negative_sampling
      bounds: [1, 1000]                       #train_type = negative_sampling
      log_scale: True                         #train_type = negative_sampling
    - name: negative_sampling.num_negatives_o #train_type = negative_sampling
      type: range                             #train_type = negative_sampling
      bounds: [1, 1000]                       #train_type = negative_sampling
      log_scale: True                         #train_type = negative_sampling
    - name: negative_sampling.shared
      type: fixed
      value: True
    - name: negative_sampling.implementation
      type: fixed
      value: batch

    # model-specific entries
    - name: transe.l_norm
      type: choice
      values: [1.0, 2.0]
      is_ordered: True
    - name: transe.entity_embedder.type_embedder.normalize.p
      type: choice
      values: [-1.0, 2.0]
    - name: transe.entity_embedder.base_embedder.normalize.p
      type: choice
      values: [-1.0, 2.0]
    - name: transe.relation_embedder.normalize.p
      type: choice
      values: [-1.0, 2.0]

    #
    - name: entity_ranking.chunk_size
      type: fixed
      value: 1024

    # model-specific entries
    - name: transe.entity_embedder.attn_nhead
      type: fixed
      value: 1

    - name: transe.entity_embedder.add_entity_to_keyvalue
      type: choice
      values: [true, false]
    - name: transe.entity_embedder.entropy_mode
      type: fixed
      value: max
    - name: transe.entity_embedder.entropy_threshold
      type: range
      bounds: [0.00001, 1.]
      log_scale: True
    - name: transe.entity_embedder.entropy_scale
      type: range
      bounds: [0.1, 10.]
      log_scale: True
    - name: transe.entity_embedder.entropy_damping
      type: range
      bounds: [0.1, 10.]
      log_scale: True
