modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]
job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transe
dataset:
  name: fb15k-237-typed
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
  num_workers: 2
import:
- transe
- type_attentive_embedder
- reciprocal_relations_model
model: reciprocal_relations_model
negative_sampling:
  num_samples:
    s: 51
    p: -1
    o: 9
  shared: true
  implementation: batch
train:
  auto_correct: true
  batch_size: 256
  loss: kl
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    factor: 0.95
    mode: max
    patience: 2
    threshold: 0.0001
  max_epochs: 125
  num_workers: 0
  optimizer:
    default:
      type: Adagrad
      args.lr: 0.03608244354696689
    type_attentative:
      regex: .*entity_embedder\.(self_attn|mi_proj).*
      args.lr: 0.3973413399833552
  type: negative_sampling
lookup_embedder:
  dim: 128
  initialize: uniform_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 0.16656778075625914
    uniform_:
      a: -0.4520140318324509
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize: ''
  regularize_args.weighted: false
reciprocal_relations_model:
  base_model:
    type: transe
transe:
  entity_embedder:
    type: type_attentive_embedder
    attn_nhead: 1
    mi_min_threshold: -12.80668593943119
    mi_min_scale: 0.06615792335015584
    mi_min_damping: 0.03693747666415329
    base_embedder:
      dropout: -0.18137097358703613
      regularize_weight: 3.038374705146157e-15
      normalize.p: -1.0
    type_embedder:
      dropout: 0.32647563703358173
      regularize_weight: 2.3008089573657196e-07
      normalize.p: -1.0
  l_norm: 1.0
  relation_embedder:
    type: lookup_embedder
    dropout: -0.4323880150914192
    regularize_weight: 1.857246975861035e-18
    normalize.p: 2.0
entity_ranking:
  chunk_size: 1024
valid:
  every: 5
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

