modules: [kge.model, kge.model.embedder, sem_kge.model, sem_kge.model.embedder]
job:
  external_tracking:
    weights-and-biases:
      project: sem_kge
      group: transe
dataset:
  name: fb15k-237-typed
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
  num_workers: 2
import:
- transe
- type_attentive_embedder
- reciprocal_relations_model
model: reciprocal_relations_model
negative_sampling:
  num_samples:
    s: 4
    p: -1
    o: 457
  shared: True
  implementation: batch
train:
  auto_correct: true
  batch_size: 512
  loss: kl
  loss_arg: 5.290767559781671
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    factor: 0.95
    mode: max
    patience: 4
    threshold: 0.0001
  max_epochs: 125
  num_workers: 0
  optimizer:
    default:
      type: Adam
      args.lr: 0.00017528104732161985
    type_attentative:
      regex: .*entity_embedder\\.(self_attn|mi_proj).*
      args.lr: 0.6653705273288685
  type: negative_sampling
lookup_embedder:
  dim: 512
  initialize: normal_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 0.00016504122472349748
    uniform_:
      a: -0.15035534471389833
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize: l1
  regularize_args.weighted: True
reciprocal_relations_model:
  base_model:
    type: transe
transe:
  entity_embedder:
    type: type_attentive_embedder
    attn_nhead: 1
    mi_min_threshold: -4.400739558041096
    mi_min_scale: 0.02301142083565282
    mi_min_damping: 1.7479820087405986
    base_embedder:
      dropout: -0.00843233335763216
      regularize_weight: 8.491592776710134e-17
      normalize.p: 2.0
    type_embedder:
      dropout: -0.37105869222432375
      regularize_weight: 4.462872602737171e-16
      normalize.p: 2.0
  l_norm: 2.0
  relation_embedder:
    type: lookup_embedder
    dropout: -0.3327635070309043
    regularize_weight: 2.0670865675836133e-05
    normalize.p: -1.0
entity_ranking:
  chunk_size: 1024
valid:
  every: 5
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

